# Generated by Django 3.0.8 on 2020-07-16 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('remote', models.BooleanField(default=False)),
                ('company_logo', models.URLField()),
                ('No_of_Assignments', models.IntegerField()),
                ('if_updated', models.BooleanField(default=True)),
                ('No_of_Openings', models.IntegerField()),
                ('tags', django_mysql.models.ListTextField(models.CharField(max_length=100), default='', size=None)),
                ('Description', models.TextField(default='')),
                ('tech_stack', django_mysql.models.ListTextField(models.CharField(max_length=100), default='', size=None)),
                ('openings_tags', django_mysql.models.ListTextField(models.CharField(max_length=100), default='', size=None)),
                ('location', django_mysql.models.ListTextField(models.CharField(max_length=100), default='', size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.URLField()),
                ('tech_stack', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
