# Generated by Django 3.0.8 on 2020-07-16 08:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20200716_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='No_of_Assignments',
        ),
        migrations.RemoveField(
            model_name='company',
            name='No_of_Openings',
        ),
        migrations.RemoveField(
            model_name='company',
            name='if_updated',
        ),
        migrations.RemoveField(
            model_name='company',
            name='location',
        ),
        migrations.RemoveField(
            model_name='company',
            name='openings_tags',
        ),
        migrations.RemoveField(
            model_name='company',
            name='remote',
        ),
        migrations.RemoveField(
            model_name='company',
            name='tech_stack',
        ),
        migrations.AlterField(
            model_name='company',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), blank=True, size=None),
        ),
    ]
