# Generated by Django 3.0.8 on 2020-07-16 08:11

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20200716_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='No_of_Assignments',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='No_of_Openings',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='if_updated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=django_mysql.models.ListTextField(models.CharField(max_length=100), default='', size=None),
        ),
        migrations.AddField(
            model_name='company',
            name='openings_tags',
            field=django_mysql.models.ListTextField(models.CharField(max_length=100), default='', size=None),
        ),
        migrations.AddField(
            model_name='company',
            name='remote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='tech_stack',
            field=django_mysql.models.ListTextField(models.CharField(max_length=100), default='', size=None),
        ),
    ]
