# Generated by Django 3.0.8 on 2020-07-16 08:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20200716_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='openings_tags',
        ),
        migrations.RemoveField(
            model_name='company',
            name='tech_stack',
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=5000), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='company',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=5000), blank=True, size=None),
        ),
    ]
